server {
    # nginx будет слушать 80 порт внутри контейнера
    listen 80;

    # корень со статическими файлами фронта
    root /usr/share/nginx/html;

    # главный файл сайта
    index index.html;

    location / {
        # если файл не найден, отдаём index.html
        # это обязательно для React SPA с роутами
        try_files $uri $uri/ /index.html;
    }
}