import React from "react";

const CheckoutLayer = () => {
  return (
    <div>
      CheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayerCheckoutLayer
    </div>
  );
};

export default CheckoutLayer;
