import React from "react";

const InfoLayer = () => {
  return (
    <div>
      InfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayerInfoLayer
    </div>
  );
};

export default InfoLayer;
