import React from "react";

const DetailsLayer = () => {
  return (
    <div>
      DetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayerDetailsLayer
    </div>
  );
};

export default DetailsLayer;
